{% set name = "responses" %}
{% set version = "0.10.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: caa5f7afd14666f970ea54a4125a639f6491218b45a013c6dc2544f0473ae2b8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - python
    - pip
  run:
    - cookies
    - python
    - requests >=2.0
    - six

test:
  imports:
    - responses

about:
  home: https://github.com/getsentry/responses
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A utility library for mocking out the `requests` Python library.

extra:
  recipe-maintainers:
    - mariusvniekerk
