{% set name = "responses" %}
{% set version = "0.25.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ebae11405d7a5df79ab6fd54277f6f2bc29b2d002d0dd2d5c632594d1ddcedb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pyyaml
    - python >={{ python_min }}
    - requests >=2.30.0,<3.0
    - types-pyyaml
    - typing_extensions
    - urllib3 >=1.25.10,<3.0
test:
  imports:
    - responses
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/getsentry/responses
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A utility library for mocking out the `requests` Python library.

extra:
  recipe-maintainers:
    - thewchan
    - mariusvniekerk
